### ISSUE TITLE
Feature: Option to auto wrap dockables in JScrollPane

### ISSUE THREAD

**Issue by tlf30** [andrewauclair/ModernDocking#103]
Hello,
I'm not sure if you would be interested in this one. How about an option to auto wrap the dockable in a JScrollPane for when the docking area is too small to display the entire dockable?

Perhaps this would be a setting on the root docking pane, or maybe on the dockable itself.

Thanks,
Trevor

**Comment by andrewauclair** [comment]
I probably should look into adding it, at least as an optional. We have some at work that need it.

**Comment by andrewauclair** [comment]
This has been implemented. I think in the future I will consider a way to gain access to the `JScrollPane`.
