### ISSUE TITLE
Question on icons

### ISSUE THREAD

**Issue by tlf30** [andrewauclair/ModernDocking#105]
Hello, I am wondering, when setting the icon of a Dockable, I'm not seeing a change. 
The icon is not displayed in the tabs (using the new style tabs), and is not displayed as the icon in the popup windows when the Docable is undocked. 

I think maybe I'm missing something. 

So I guess two questions:
1. How do I set the icon on the tab (or is it possible yet when using the new style tabs)?
2. How do I set the icon on the undocked Dockable window. Ideally this would be independent of the Dockables since multiple dockables can be in a single window.

Thanks,
Trevor

**Comment by andrewauclair** [comment]
I think it should work in both cases from what I can remember right now. I will investigate.

**Comment by andrewauclair** [comment]
Turns out that calling `setTabComponentAt` overrides `setIconAt`. I fixed this by setting the icon on the `JLabel` that I set as the tab component.

**Comment by tlf30** [comment]
Just loaded up 0.8.1 (thank you for getting this update out so quick!)
I am testing icons in the tabs, they are working good. 

For additional undocked windows, could you create a way to set the icon for those? Perhaps globally?
![image](https://github.com/andrewauclair/ModernDocking/assets/10089434/2fd3d924-a294-400c-8b95-e287a9c81175)

I also noticed that the icons in the tabs grow to the size of the icon, and are not restricted to the normal size of the tab.
Note sure how I feel about this (I just have not decided) Should the tab force the icon to resize to the correct size, or should the developer provide the correct size icon? I'll leave that up to you. In my case I am providing a 32x32 icon for testing just to show the increase in the tab size. 

![image](https://github.com/andrewauclair/ModernDocking/assets/10089434/55055b73-ee99-40d9-9210-3561e1c00ed6)

**Comment by andrewauclair** [comment]
Interesting. I would say they should get set to a fixed size like the normal tab icons. I'll see how the normal JTabbedPane works.

**Comment by andrewauclair** [comment]
Looks like the tabs on JTabbedPane do the same thing. Looks like it's up to the developer to provide an appropriately sized icon for the tab. I'll keep mine the same.

![image](https://github.com/andrewauclair/ModernDocking/assets/2949516/c4f2a113-5b1d-4062-bc8d-8018379a26c9)

**Comment by andrewauclair** [comment]
Changed added to main for 0.9.0 release.
