### ISSUE TITLE
Snapshots

### ISSUE THREAD

**Issue by tlf30** [andrewauclair/ModernDocking#112]
Hello,
Perhaps I am doing something wrong, but I cannot find snapshots for any versions newer than 0.3.0.
Are there recent snapshots?

The README should probably be updated to reflect the state of snapshots, or the configuration information for updated snapshots.

If there are not newer snapshots, would you consider getting them setup again?

Thanks,
Trevor

**Comment by andrewauclair** [comment]
Looks like I haven't done one with the new package names. I'll do that for 1.10 so it's tracked.

I'll try to make it more of a habit to make snapshots for each version.

**Comment by andrewauclair** [comment]
0.10.0-SNAPSHOT is now available.

**Comment by andrewauclair** [comment]
Sonatype exclusively uses s01 now. Looks like I had updated the link in the README, but not the text I display for what repo to add. I have updated that to reference s01 as well.
