### ISSUE TITLE
Ability to re-initialize docking api

### ISSUE THREAD

**Issue by tlf30** [andrewauclair/ModernDocking#133]
Hello,
I was wondering if you could add a way to uninitialized and re-initialize the docking api for the `single` package. 
Currently the initialize function no longer does anything once the docking api is initialized:
```
public static void initialize(Window mainWindow) {
        if (instance == null) {
            instance = new DockingAPI(mainWindow){};
        }
    }
```
Perhaps it could re-initialize if the provided window is different from the given window.

Also, an `uninitialize()` function would be useful to set the `instance` to null. This would be for releasing the reference to the main window so GC can clean it up once it is no longer needed. In my app, the main window will some times get disposed of, and later a new main window will get created. Mostly when major things like loading a new license file happens. Also the uninitialize would be useful for shutdown since the docking api holds the reference to the main window after it was disposed, so it never gets cleaned up before the jvm exists, meaning any cleaners associated with the main windows resources never get run.  

The uninitailize may also need to call 
```
instance.deregisterAllDockingPanels();
instance.deregisterAllDockables();
```
before setting the instance to null just to ensure any hanging windows get disposed of correctly. 

Thoughts?

Thank you,
Trevor

**Comment by andrewauclair** [comment]
I like it. Having a way to completely teardown the framework would be good.
