### ISSUE TITLE
Get list of dockables from instance

### ISSUE THREAD

**Issue by tlf30** [andrewauclair/ModernDocking#134]
Hello,
I did not see it, but maybe I missed it, could you please add a getter for the list of Dockables in the instance?
You will probably want it to be wrapped in an unmodifiable list I would think. (`Collections.unmodifiableList`).

Thanks,
Trevor

**Comment by andrewauclair** [comment]
Wouldn't be hard. I do already have this, but it's hidden in DockingInternal.java.
