### ISSUE TITLE
Feature request: tabs at top of each ...zone

### ISSUE THREAD

**Issue by i-make-robots** [andrewauclair/ModernDocking#135]
Hi!  I've been looking for a supported docking system for my editor.  This looks like it does a lot of what I want.

Is there a way to put the tab group at the top of the group?

Is there a way to merge the tab group and the ... x buttons into a single line to save space?  the ... x buttons would apply to the currently selected tab in the group.

Thank you,

**Comment by i-make-robots** [comment]
I’m fine with a single close button that closes the currently active tab. It could even be hidden in the … or a hamburger menu to reduce clutter.Is that possible?  I’m looking to emulate a simple look like I have in IntelliJ.Sent from my iPhoneOn Nov 27, 2023, at 2:23 PM, Trevor Flynn ***@***.***> wrote:﻿
I believe I understand what you want.
Try running this after you have initialized.
//Use tabs on top of dockable
        Settings.setAlwaysDisplayTabMode(true);

**Comment by andrewauclair** [comment]
The close button is always displayed if the dockable is closable.

**Comment by SingleKey** [comment]
Docking.setAlwaysDisplayTabMode(true);

**Comment by NebelNidas** [comment]
Would be nice to have an option to show tabs at the top without having to set `alwaysDisplayTabMode` to true

**Comment by andrewauclair** [comment]
> Would be nice if tab positioning was configurable, independently of `alwaysDisplayTabMode`. Many IDEs like Visual Studio or Idea use both at the same time

Yes, that would be nice. I haven't found a great way to do that yet. For now it's one or the other.

**Comment by i-make-robots** [comment]
I'm in 0.11.0-SNAPSHOT and I can't find `Settings.*`.   I found `DockingSettings` and `Docking` but neither has `alwaysDisplayTabMode`.

**Comment by andrewauclair** [comment]
> I'm in 0.11.0-SNAPSHOT and I can't find `Settings.*`. I found `DockingSettings` and `Docking` but neither has `alwaysDisplayTabMode`.

Looks like the `ModernDocking.settings` package was not being exported from the module. A new 0.11.0-SNAPSHOT is building right now with this fix.

**Comment by i-make-robots** [comment]
For future people, the new parameter is `ModernDocking.settings.Settings.setAlwaysDisplayTabMode(true);`

**Comment by andrewauclair** [comment]
Pull request #143 now allows each dockable to set a preference for top or bottom tabs. If any tabs in a group have a preference for top tabs in the tabbed group will use top tabs.

It's a step towards making this more flexible and I hope to improve it further in the future.

**Comment by i-make-robots** [comment]
> Edit: this will put tabs on top where each tab has its own close button

Here are a few docks.  The tabs are always at the bottom.  The tabs do not have close buttons.  The dragging behavior is not always obvious:

![2023-12-12-01](https://github.com/andrewauclair/ModernDocking/assets/1464454/c3fa49bc-04e6-4bb8-a728-8da158111259)

from [this souce again](https://github.com/MarginallyClever/Robot-Overlord-App/blob/ro3/src/main/java/com/marginallyclever/ro3/RO3.java).

I can definitely work with it and it's great.  It would be nice if I could get the tabs on top and the close button.

Also why the blue edge on every panel?  How do I turn that off?  I looked in `ModernDocking.settings.Settings`.

Thanks!

**Comment by i-make-robots** [comment]
About the blue:  it seems that when i hover over a dockingpanel it turns blue and then *never stops* being blue when the cursor leaves.  Are there border color controls

**Comment by andrewauclair** [comment]
> About the blue: it seems that when i hover over a dockingpanel it turns blue and then _never stops_ being blue when the cursor leaves. Are there border color controls?

That's strange, it should stop. Sorry, I forgot to respond to this one. This is controlled by the `ActiveHighlighter` internal class. The properties of the border are controlled through properties defined in `DockingSettings`. The properties are retrieved from `UIManager` like other look and feel properties. The default swing L&F doesn't really look that great by default. I use FlatLaf in my projects and the demos here, which is what the ModernDocking UI extension is geared for.

**Comment by i-make-robots** [comment]
Since my initial request in this thread is solved, i'm closing this.  Thank you!  You rock!!
