### ISSUE TITLE
How do I close and reopen docking panels?

### ISSUE THREAD

**Issue by i-make-robots** [andrewauclair/ModernDocking#148]
I have a frame and inside that some panels.  if a user closes a panel, it should be re-open-able from `main menu > windows > [checkbox] panel name`.  Listening to DockingPanel visibility is not the right answer 😅 I didn't find the demo that gave the right advice.  Please let me know!

Also is there some way I can access the wiki and contribute things I learn as I go?  To save you the time.  I'm happy to document if only for my own needs.

**Comment by andrewauclair** [comment]
I don't think it's possible to open up the Wiki like that without opening up the entire repo. Unfortunately it looks like GitHub doesn't allow Wiki PRs? That's a real bummer. I have a couple weeks off work after this week and was going to focus on documentation. The Wiki is very out of date at this point.

As for your issue. This can be done using the `ModernDocking.app.DockableMenuItem` which extends `JCheckboxMenuItem` and can be created with the `persistentID` or a `Supplier<String>` that provides the `persistentID`. You can see how this is done in the demo here: https://github.com/andrewauclair/ModernDocking/blob/4262c215841cbd9034d14f1fd4a4206a682a2602/demo-single-app/src/basic/MainFrame.java#L276.

**Comment by andrewauclair** [comment]
Please write discussion posts for documentation issues. We can then write issues if there's something that needs to change. I'm going to swap to a docs folder in the repo (like [Catch2](https://github.com/catchorg/Catch2/tree/devel/docs)) that way I can accept PRs for them.

**Comment by andrewauclair** [comment]
> Awesome! It definitely reopens the panels. If I click on a DockableMenuItem it does not close the window, nor does it highlight the window to point out where it already exists.

`DockableMenuItem` will dock the dockable if it is not docked and display it if it is docked. If the dockable is already at the front of a tab group then display does nothing. But if the dockable is in a tab that isn't visible, display will make it the selected tab.

Currently it doesn't highlight the dockable. It might be possible, but Swing is a little odd to work with in that department and really lacks animation features.
