### ISSUE TITLE
Consider Merging More Functions into the Docking Class

### ISSUE THREAD

**Issue by andrewauclair** [andrewauclair/ModernDocking#168]
Monolithic classes probably aren't perfect design, but I believe it keeps this framework simpler if there's only one major class to interact with. I'll add a list to this issue later of what exactly should be added into `Docking`.

**Comment by tlf30** [comment]
I'm trying to remember as it has been some time, IIRC a lot of the AppState logic originally was in the Docking class right?

**Comment by andrewauclair** [comment]
Looking back through the history it looks like it has always been separate.

**Comment by tlf30** [comment]
Ah, I wonder what I am remembering... You have changed so many things over the years now I do not remember. I do remember at some point breaking something out of some class.... 

I have no preference either way, it is as simple as bulk replacing a reference. And for my projects, I have a single class that manages most of the docking infrastructure, and a second class for a custom dockable, so making changes is quite simple.

**Comment by andrewauclair** [comment]
I think I'll just close this for now. I can remember specifically what functions I wanted to move. If I can't remember, then it must not be a big deal.
