### ISSUE TITLE
Docking Function to Check if Dockable with Persistent ID is Registered

### ISSUE THREAD

**Issue by andrewauclair** [andrewauclair/ModernDocking#186]
Simple function in the `Docking` class to check if a dockable is registered. Pretty sure this doesn't exist. I don't see it.

**Comment by tlf30** [comment]
This will be handy. Currently I keep track of what persistent ids are registered in my code.

**Comment by andrewauclair** [comment]
Yeah, I had to just roll my own like this for now:

```java
boolean panelWithTitleExists(String name) {
	return Docking.getDockables().stream().anyMatch(dockable -> dockable.getPersistentID().equals(name));
}
```
