### ISSUE TITLE
MVN repository central releases

### ISSUE THREAD

**Issue by KlemenDEV** [andrewauclair/ModernDocking#211]
Hey,

it seems the last non-snapshot release on maven central is 0.8.2 (https://mvnrepository.com/artifact/io.github.andrewauclair.ModernDocking/ModernDocking).

Would it be possible to get the latest releases on central too?

**Comment by KlemenDEV** [comment]
Never mind, package names changed. All good :) Sorry for the false alarm.

**Comment by andrewauclair** [comment]
I had this issue myself the other day. I believe I searched "ModernDocking" and got the old packages. Had to use "modern docking". I'm not sure I can do much about that. Maybe I can delete the older stuff.

**Comment by Shadowblitz16** [comment]
Doesn't exist as far as intelliji is concerned

**Comment by andrewauclair** [comment]
> Doesn't exist as far as intelliji is concerned I typed "modern docking" into the search field

Looks like a lot of people have issues with that. Looks like it only shows snapshot versions for me and not any of the modern docking ones. Here's some search results for them https://search.maven.org/search?q=modern%20docking.
