### ISSUE TITLE
Package name should be lower-case

### ISSUE THREAD

**Issue by KlemenDEV** [andrewauclair/ModernDocking#212]
Package names such as "ModernDocking.app" should be lower-case, "moderndocking.app"

See https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html#:~:text=Naming%20Conventions,a%20programmer%20at%20example.com%20.

**Comment by andrewauclair** [comment]
I don't see any reason to rename the packages at this point. The library is already in use, and package renames are a pain.

**Comment by KlemenDEV** [comment]
I see. I was merely suggesting it, as seeing package names starting uppercase is quite uncommon with Java (actually maybe the first time I have seen something like that in a bigger Java library).

A counterargument for renaming packages at this point may be that most modern IDEs allow very easy refactoring of package names if it comes to it.

But yes if the package name was to be renamed, it would need the major version number change (in semver terms).

But I usually go with better do something right sooner than later and thus wanted to point it out ;)

**Comment by andrewauclair** [comment]
I'm warming up to this one. I can't resist a giant refactor. I think the packages should probably be `io.github.andrewauclair.moderndocking` which is why I'm thinking of actually changing it. That way it matches maven.

**Comment by tlf30** [comment]
As a 1.0 I'm not opposed to this. It will be a large amount of work on my end, but that is why IDEs have a refractor function.

**Comment by andrewauclair** [comment]
> As a 1.0 I'm not opposed to this. It will be a large amount of work on my end, but that is why IDEs have a refractor function.

I'm making some changes for 0.12 that should hopefully help a lot with this. The new `io.github.andrewauclair.moderndocking` package will be available starting with 0.12 and the existing `ModernDocking` package will be deprecated. I'm sure this will cause an enormous number of warnings, but it will at least not force converting immediately. The `ModernDocking` package will then be removed in the 1.0 release.

These changes (along with some other 0.12 changes) are available as `0.12.0-SNAPSHOT` now.
