### ISSUE TITLE
Maven dependencies

### ISSUE THREAD

**Issue by KlemenDEV** [andrewauclair/ModernDocking#213]
The library declares some maven dependencies as runtime, but should likely be compile.

For example modern-docking-multi-app declares modern-docking-api as runtime dependency, but not explicitly importing API results in build errors, meaning dependency should be compile-time.

**Comment by andrewauclair** [comment]
Turns out you have to use `api` instead of `implementation` to make a proper transitive compile time dependency. I made the changes and published a 0.11.3 which I'll test out in the morning when it finally shows up on central.

**Comment by KlemenDEV** [comment]
Thanks!

**Comment by andrewauclair** [comment]
Looks good in 0.11.3. Just need to put this in main for future releases.

**Comment by KlemenDEV** [comment]
Tested, it works with 0.11.3, thanks! :)

**Comment by tlf30** [comment]
I'll test tonight on my apps too. It will give me a reason to finally update to 0.11 (I've been busy and just haven't gotten to it even though it has fixes I need).

**Comment by andrewauclair** [comment]
Added fixes for 0.12 and some new 0.11 fixes that make the build work properly. A new release isn't needed, but it will be helpful if I decide to make another 0.11 build.

**Comment by tlf30** [comment]
Just ran a quick test. Everything looks like it is working. All my plugins are inheriting the dependencies correctly.
