### ISSUE TITLE
Improve logging / remove debug messages

### ISSUE THREAD

**Issue by KlemenDEV** [andrewauclair/ModernDocking#217]
There seem to be some logging messages that are printed. This one is printed especially often: https://github.com/andrewauclair/ModernDocking/blob/3fa9a8c118ba5ae70c827d23f2ff598799c3274f/docking-api/src/ModernDocking/floating/DockingOverlay.java#L391

This should probably be removed or put under some sort of parameter

**Comment by nroduit** [comment]
I would recommend using the [sl4j](https://slf4j.org/) facade to manage log levels and abstract the logger used.

For the tests, you can use the Simple package:
```xml
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-simple</artifactId>
      <scope>test</scope>
    </dependency>
```

**Comment by tlf30** [comment]
I personally use log4j. But any logger is alright. Just note that dependencies on loggers suck for apps that are not using a logger. For apps that use a logger, there are adapters from just about any logger to anything...
