### ISSUE TITLE
Dockable window operations prevents application to terminate

### ISSUE THREAD

**Issue by makiam** [andrewauclair/ModernDocking#223]
Reproduced on Ubuntu Linux with Azul Java 19
Steps to reproduce:
I have MainWIndow with single dockable panel and my window is set to dispose on close flag. (i.e this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE); )
Once I run and close window immediately, the application automatically closes as no more top-level windows in it.
Once I run app, detach dockable and dock it back or detach and close float window and then close main window, the application is no more terminates. (I assume some top-level windows is left and prevents to close app)

**Comment by andrewauclair** [comment]
The proper way (imo) to do this is to use `setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);`

That way the application closes when that `JFrame` is closed, no matter what other windows are open.

**Comment by andrewauclair** [comment]
That said, it does look like Modern Docking doesn't call `setDefaultCloseOperation` for the `TempFloatingFrame` and `JFrame` defaults to `HIDE_ON_CLOSE`. I'll put a fix in for that.

**Comment by andrewauclair** [comment]
Fixed in 0.11.6.
