### ISSUE TITLE
Docking background color

### ISSUE THREAD

**Issue by tlf30** [andrewauclair/ModernDocking#243]
Hello 
I am seeing an issue where then there is no dockable in the root docking pane that is full screen, but there are ones pinned. Then the background is white instead of the correct LAF color. 

![image](https://github.com/user-attachments/assets/3871d7a0-bfc6-4d52-9d28-3d67554e9db0)

**Comment by andrewauclair** [comment]
Interesting. I have not seen this. Have you been able to reproduce it an example? The only place the background color should be set is the headers of a docking panel.

**Comment by andrewauclair** [comment]
@tlf30 I'm hoping that the change I just made will fix the issue. There is an empty panel in all `RootDockingPanel`s that can be set (in case you want to display some sort of message when the root is empty). This panel was not being updated when switching Look and Feel.
