### ISSUE TITLE
possibility to veto close-request

### ISSUE THREAD

**Issue by warmuuh** [andrewauclair/ModernDocking#244]
i am using `setAlwaysDisplayTabMode(true)` for an editor-like application where multiple files are open.

I would like to ask the user, if he really wants to close a tab, if the file is dirty. I saw that you use the `JTabbedPane.tabCloseCallback` property to trigger `DockingAPI::undock` but I cant see a way to prevent this operation if the tab should reject.

would it be possible to have another method `requestClose` (or any better name) next to `isClosable` which, if returning false, cancels the  tabCloseCallback?
or allowing us to customize the close-callback without resorting to reflection

**Comment by andrewauclair** [comment]
Sounds like an interesting idea to me. I'll look into it soon.
