### ISSUE TITLE
Recommendations for compatibility with other APIs

### ISSUE THREAD

**Issue by tlf30** [andrewauclair/ModernDocking#39]
Hello,
First I want to say thank you for building this great library.

I have a couple recommendations that would make the library much simpler to integrate into applications.

First, it would be great to have no-arg constructors, this would make using the components with UI building tools like JFormDesigner much simpler. 

Second, having the properties in the components compatible with JSR 295 like other Swing components would a huge improvement as it adds support for using property bindings like JDesktop's beansbindings. 

I recognize that this would be a large change in the API to implements. 

Thank you,
Trevor

**Comment by andrewauclair** [comment]
Thanks! This has been a fun side project.

I will give those a look. I haven't used JFormDesigner before. I prefer to build my Swing GUIs manually and not rely on builders. But it does look like a fun tool. I really love FlatLaf and have been using that for a year or so (just before I started this project).

**Comment by tlf30** [comment]
Thank you,
I must say I just recently started using JFormDesigner. I got a 3 year license, and it paid for itself in the first day. I got a very large complicated UI built in just hours, and that was trying to learn the tool at the same time. I am using it as an IDEA plugin.

**Comment by andrewauclair** [comment]
Got an evaluation copy of JFormDesigner and playing around with fixing some of the panels. Shouldn't be too difficult to fix the `RootDockingPanel` in a way that mostly works. I realized that forcing `RootDockingPanel` to be in a `JFrame` might be tough to live with at some point, so I wrote an issue for that. Although changing it will be difficult because the entire framework currently relies on `JFrame`s.

I think it will be somewhat usable from JFormDesigner if I fix `RootDockingPanel` and provide a way to create docking panels as individual jfd files (as something that implements `DockingPanel` maybe, like `RootDockingPanel` does). Then configuring the docking would still be manual like in my current demos.

Creating the default layouts from within a jfd sounds like an interesting idea, but I'll have to learn JFormDesigner better before tackling that. Not sure how much of Modern Docking can be done from within JFormDesigner as I heavily control how the docking panels are added to the `RootDockingPanel`, `JSplitPane` and `JTabbedPane`.

**Comment by tlf30** [comment]
Just being able to drop the RootDockingPanel and have it work would be great. I looked at some of the changes, and the largest issue was the constructor. Most swing components support a no-arg constructor and that was what it is JFormDesigner expecting. 

And being able to build a JFormDesigner UI using the Dockable Panel as the base (Instead of a JPanel or JFrame). Wiring the two together is code would be fine (I image it would be far to complicated to get JFormDesigner to understand dropping the DockingPanel on to the RoockDockingPanel. 
Having JSR 295 would mean that any library or tools that utilize bean binding would be able to bind to the components, which is how JFormDesigner finds properties (Along with NetBeans UI editor and JetBrains UI editor). But most importantly it would give the ability to have dynamic bindings. JSR 295 is super clunky and a terrible implementation design, but it is what we got, and that is what swing and AWT use internally for events as well. 

Thank you so much for the quick responses and looking into this, let me know if you have any questions or if there is anything I can help with.

**Comment by andrewauclair** [comment]
No problem! It's exciting to have someone interested in the project haha.

I was planning on putting out a 0.4.0 next weekend with more changes, but hadn't come up with much yet, so you came at just the time haha. I'll get the RootDockingPanel fixed up.

**Comment by andrewauclair** [comment]
The last couple weeks have been a very busy nightmare, but, I just released 0.4.0 to maven central with some changes for this issue. I've also done a bunch of renaming to standardize some stuff better, sorry in advance.

If you wouldn't mind trying it out and letting me know what else I can change that would be great.

**Comment by tlf30** [comment]
No worries, thank you! 
I reviewed a few of the changes here on github, and they look great.
I will work on integrating it into my app today and get some feedback put together for you. 
Thank you so much for working on this library, I think it is a great match for the projects I am working on.

**Comment by tlf30** [comment]
OK, this is great. I have a basic implementation working and am working out the bugs.
It would be good to have a null check on the west, east, and south toolbars for getting the IDs for when the toolbars do not exist.
Returning null would be fine.
https://github.com/andrewauclair/ModernDocking/blob/5040426da79b284dcb27d1be60bb41d8c2fccbd0/docking/src/ModernDocking/RootDockingPanel.java#L304

**Comment by andrewauclair** [comment]
Possibly. To make the RootDockingPanel work properly you have to call setWindow when you're using the no args constructor for it to properly register and create the toolbars. But yes, I should fix that to return an empty list if the toolbars haven't been created yet.

**Comment by tlf30** [comment]
Yep, just when previewing the window in JFormDesigner, it goes crazy with errors when grabbing those properties. Not an issue at runtime.

A couple of other things:
I cannot get the pinning options to show on the header, and I am getting an issue where after dragging and redocking a panel a couple times the application freezes (no stack trace)

Panel code:
```java
public class ToolPanel extends JPanel implements Dockable {

    private final String name;

    /**
     * Constructor for JFormDesigner, do not use
     */
    public ToolPanel() {
        this.name = Integer.toHexString(hashCode());
    }

    public ToolPanel(String name) {
        this.name = name;

        // register the dockable with the Docking framework in order to use it
        Docking.registerDockable(this);
    }

    @Override
    public String getPersistentID() {
        return name;
    }

    @Override
    public int getType() {
        return 0;
    }

    @Override
    public String getTabText() {
        return name;
    }

    @Override
    public Icon getIcon() {
        return null;
    }

    @Override
    public boolean isFloatingAllowed() {
        return true;
    }

    @Override
    public boolean shouldLimitToRoot() {
        return false;
    }

    @Override
    public DockableStyle getStyle() {
        return DockableStyle.BOTH;
    }

    @Override
    public boolean canBeClosed() {
        return false;
    }

    @Override
    public boolean allowPinning() {
        return true;
    }

    @Override
    public boolean allowMinMax() {
        return false;
    }

    @Override
    public boolean hasMoreOptions() {
        return false;
    }
}
```

**Comment by andrewauclair** [comment]
> Yep, just when previewing the window in JFormDesigner, it goes crazy with errors when grabbing those properties. Not an issue at runtime.
Ah, now it makes total sense.

> A couple of other things: I cannot get the pinning options to show on the header, and I am getting an issue where after dragging and redocking a panel a couple times the application freezes (no stack trace)
With the default headers the pinning options are only displayed if `hasMoreOptions` returns true.

> But after a panel has been moved, running Docking.dock(messageTool, this); no longer adds a tab
I'll play around with this later. I suspect that nothing happens docking wise, but part of the code probably assumes something does happen. I'll have to think about what should be done in this case. Docking to the root CENTER doesn't make sense once there's a split.

**Comment by tlf30** [comment]
OK, for the pinning button not showing, I have found they do exist (But are very very small, not visible) If I click enough I will hit them. The same issue applies to the close button.  This was tested with hasMoreOptions set to false and true.

You can see here, where I have highlighted the more options button with my mouse. In this screenshot, hasMoreOptions is set to true.

![image](https://github.com/andrewauclair/ModernDocking/assets/10089434/718280b9-4f79-4cf5-8a7b-8c883bbd075e)


```
package io.tlf.cip.tool.ui.components;

import ModernDocking.Dockable;
import ModernDocking.DockableStyle;
import ModernDocking.Docking;
import io.tlf.cip.tool.ui.events.OpenToolEvent;
import io.tlf.cip.tool.ui.events.OpenToolListener;
import io.tlf.cip.tool.ui.events.ToolUndockedEvent;
import io.tlf.cip.tool.ui.events.ToolUndockedListener;

import javax.swing.*;

public class ToolPanel extends JPanel implements Dockable {

    private final String name;

    /**
     * Constructor for JFormDesigner, do not use
     */
    public ToolPanel() {
        this.name = Integer.toHexString(hashCode());
    }

    public ToolPanel(String name) {
        this.name = name;

        // register the dockable with the Docking framework in order to use it
        Docking.registerDockable(this);
    }

    public void addToolUndockedListener(ToolUndockedListener listener) {
        listenerList.add(ToolUndockedListener.class, listener);
    }

    public void remoteToolUndockedListener(ToolUndockedListener listener) {
        listenerList.remove(ToolUndockedListener.class, listener);
    }

    private void fireToolUndocked() {
        Object[] listeners = listenerList.getListenerList();
        for (int i = 0; i < listeners.length; i += 2) {
            if (listeners[i] == ToolUndockedListener.class) {
                ((ToolUndockedListener) listeners[i + 1]).onToolUndocked(new ToolUndockedEvent(this, this));
            }
        }
    }

    @Override
    public void onUndocked() {
        fireToolUndocked();
    }

    @Override
    public String getPersistentID() {
        return name;
    }

    @Override
    public int getType() {
        return 0;
    }

    @Override
    public String getTabText() {
        return name;
    }

    @Override
    public Icon getIcon() {
        return null;
    }

    @Override
    public boolean isFloatingAllowed() {
        return true;
    }

    @Override
    public boolean shouldLimitToRoot() {
        return false;
    }

    @Override
    public DockableStyle getStyle() {
        return DockableStyle.BOTH;
    }

    @Override
    public boolean canBeClosed() {
        return true;
    }

    @Override
    public boolean allowPinning() {
        return true;
    }

    @Override
    public boolean allowMinMax() {
        return false;
    }

    @Override
    public boolean hasMoreOptions() {
        return true;
    }
}
```

**Comment by andrewauclair** [comment]
That is very strange. Almost looks like the icon isn't on the button.

**Comment by tlf30** [comment]
> That is very strange. Almost looks like the icon isn't on the button.

Agreed,
Also another NullPinterException for JFromDesigner is the `getRootPanels` on the RootDockingPanel, it could just return null.

**Comment by tlf30** [comment]
So on the freezing issue, it happens when dragging a panel brefore dropping it. With 2 panels it is more difficult to reproduce, takes about 10 drops. With 3 or more panels it can be reproduced in 1 to 3 drops usually. The east drop point seems to be the most problematic with the top and bottom the least, but that could just be bias in my testing. 
I ran the debugger trying to get a stack trace of where it was, but it was deep in the awt code hung on `disableNativeIME` 

OK, so I have changed JDKs from v17 to v19. It seems to fix the issue. Seems like the freezing was a JDK problem. 

Also, this is great. Thank you for all your hard work on this library. I am getting it fully integrated, and it is working really well aside from just the issues above. 
![image](https://github.com/andrewauclair/ModernDocking/assets/10089434/8f2795c7-f363-403b-b8ce-ddc58ae425cc)

Next I will try to figure out what is causing the icons to not show on the panel title bars.

**Comment by tlf30** [comment]
OK, for the icons, the `ModernDocking-0.4.0.jar` is missing the resource png files. 
It looks like this line from the gradle build may be missing: `sourceSets.main.resources.srcDirs = ['resources']`

**Comment by andrewauclair** [comment]
> OK, for the icons, the `ModernDocking-0.4.0.jar` is missing the resource png files. It looks like this line from the gradle build may be missing: `sourceSets.main.resources.srcDirs = ['resources']`

Good catch. I assumed you were using ModernDockingUI as well like I am. Looks like I have the icons correct in ModernDockingUI (where I use .svg files) but not in ModernDocking where they are .png. I will get that fixed too.

**Comment by tlf30** [comment]
Thanks, I have not swapped over to the SVG icons yet. I was something on my list to look at.

**Comment by andrewauclair** [comment]
> > That is very strange. Almost looks like the icon isn't on the button.
> 
> Agreed, Also another NullPinterException for JFromDesigner is the `getRootPanels` on the RootDockingPanel, it could just return null.

I'm not sure exactly what you mean here. Does JFormDesigner actually manage to call the Docking.getRootPanels function from somewhere?

**Comment by tlf30** [comment]
Yes, it calls all property getters to populate the properties menu:
![image](https://github.com/andrewauclair/ModernDocking/assets/10089434/f451653a-9450-40df-b9be-e1e59d36d719)

Basically any getter should be safe to call at any time, even if it only returns null.

**Comment by andrewauclair** [comment]
Ok I think I finally got that one figured out. I keep forgetting I have to rebuild for JFormDesigner to pick up the changes. JFormDesigner was removing the panel, causing removeNotify to trigger and attempt calling the Docking instance.

**Comment by tlf30** [comment]
Ah yeah. A recompile, and then I usually hit the JFormDesigner refresh button in its top toolbar as it really forces it to pick up the changes. 
Thank you for working on this, I am really excited for it. I am doing quite a bit of testing right now, and it is working really well. 
The persistent layout is amazing. I have prepared my code for the Panels to save some properties, which I will be mostly using for saving my split pane divider positions.

**Comment by andrewauclair** [comment]
Awesome! Let me know how the `getProperties`/`setProperties` work out. I added them because I have one panel at work where I want to persist the order and sizes of columns in a JTable.

I am currently fixing a bunch of issues with the layout builders. I never really tested them and they are apparently very broken.

**Comment by tlf30** [comment]
I updated to 0.4.1, Things are looking much better. 

I am going to look on my side how to configure default docking behavior for my different tools. 
Some tools I want to initially dock on the right, left or bottom, and some I want to add tabs to the center.  
![image](https://github.com/andrewauclair/ModernDocking/assets/10089434/82925c55-db83-48ad-9536-243fa8085698)

Thank you so much for all your work on this yesterday

**Comment by andrewauclair** [comment]
@tlf30 anything else that should be done for this issue or are we good?

**Comment by tlf30** [comment]
I think everything is good to go on this. Everything I need for beansbinding I have implemented as part of the `Dockable` interface in my implementation. The API as it stands is very flexable and allows for easy integration. If I run into anything I will make a new issue. 

Thanks for all the work on this, it really helped get everything working.
