### ISSUE TITLE
Allow Custom Persistence per Dockable

### ISSUE THREAD

**Issue by andrewauclair** [andrewauclair/ModernDocking#50]
I would like to persist custom information per dockable (information about which columns are displayed in a JTable). This should be either functions right on the Dockable interface or another interface that can be used to register a handler.

**Comment by andrewauclair** [comment]
This is only working as a simple panel, not as a tab.

**Comment by tlf30** [comment]
This would be fantastic. I was just starting to look at this and I saw you already had an issue for it.

**Comment by tlf30** [comment]
I took a look at the commit you submitted for this. I think that will work fine. It is a simple and easy solution that will fit most use cases.

**Comment by andrewauclair** [comment]
If you have some ideas for something better, let me know. `Map<String, String>` kind of sucks in terms of design depth in the API, but like you said, is simple and leaves it up to the app as much as possible.

**Comment by tlf30** [comment]
It would be nice to be able to persist the other primitives, at least float, int, and boolean. But String is a great starting point because anything can be written to it. So for now I am happy with just having strings. 

Something that can be done (I am not diving into the XML save code here)
```java
Map<String, Object> properties = new HashMap<>();

        for (String key : properties.keySet()) {
            var obj = properties.get(key);
            if (obj instanceof String str) {
                    //TODO: Save property
            } else if (obj instanceof Integer) {
                //TODO: Save property
            }
            //Other types
            else {
                throw new IllegalArgumentException("Invalid type for persistent property: " + obj.getClass().getName());
            }
        }
```
Just throw an exception on an unsupported type. 

The XML could save each property like so:
```xml
<properties>
    <property key='key name' type='String'>some value</property>
    <property key='key name' type='Integer'>42</property>
    ....
</properties>
```

**Comment by tlf30** [comment]
I upgraded to 0.4.1, and am trying out the persistence. 
I have setup my persistence code like so:
```
private void changeView(ActionEvent e) {
    if (changeView.isSelected()) {
        discoveryPanel.setOrientation(JSplitPane.VERTICAL_SPLIT);
    } else {
        discoveryPanel.setOrientation(JSplitPane.HORIZONTAL_SPLIT);
    }
    getProperties().put("orientation", Integer.toString(discoveryPanel.getOrientation()));
    AppState.persist();
}
private void discoveryPanelPropertyChange(PropertyChangeEvent e) {
    getProperties().put("dividerLocation", Integer.toString(discoveryPanel.getDividerLocation()));
    AppState.persist();
}
```

I have confirmed that the properties are set.
Here is what the generated layout looks like:
```
<?xml version="1.0" ?>
<app-layout>

<layout main-frame="true" location="-8,-8" size="2576,1416" state="6">
<westToolbar>
</westToolbar>
<eastToolbar>
</eastToolbar>
<southToolbar>
</southToolbar>
<split orientation="1" divider-proportion="0.11193738132715225">
<left>
<simple persistentID="Discovery">
<properties></properties>

</simple>
</left>
<right>
<split orientation="0" divider-proportion="0.5529500842094421">
<left>
<tabbed>
<selectedTab persistentID="Message">
</selectedTab>
<tab persistentID="Message">
</tab>
<tab persistentID="Controller">
</tab>
<tab persistentID="Factory Reset">
</tab>
</tabbed>
</left>
<right>
<simple persistentID="Message Log">
<properties></properties>

</simple>
</right>
</split>
</right>
</split>
</layout>
</app-layout>
```

**Comment by tlf30** [comment]
I figured out the issue, I have not had enough coffee this morning. I never implemented the getProperties and setProperties.

**Comment by andrewauclair** [comment]
Bit of a crazy idea, but, one of my favorite Java libraries PicoCLI does some cool dynamic stuff where it fills member variables with values from the user. I'm curious to try out doing something similar for dockable persistence.

**Comment by andrewauclair** [comment]
The basics of this have been added. I'm going to write some more issues for enhancing it.
