### ISSUE TITLE
Component visibility detection

### ISSUE THREAD

**Issue by sesquialtera87** [andrewauclair/ModernDocking#63]
There's a way for a get notifications when a `Dockable` is shown or hide?

I've found the `onDocking`, `onDocked` and `onUndocked` methods for the `Dockable` class, but I can't find a way to determine when a `Dockable` is shown/hidden while still being docked (for example, when a `Dockable` is unpinned it's no longer visible, but still docked)

I have a side panel and when the user hides it I want to release some resources and refresh the data when the panel again becomes visible, but I can't found how to listen for show/hiding events (not simply docked/undocked)

Related to the previous point, I can't find a way to detect which component become active in a tabbed dock structure.
Thanks in advance for help.

**Comment by andrewauclair** [comment]
`DockingListener` might be the best choice here, if you're trying to do this externally to `Dockable`. I will update both to have new `shown` and `hidden` options.

**Comment by sesquialtera87** [comment]
I have only now seen the `Dockable` class update with the new `shown` and `hidden` methods: that's great, exactly what I needed! Thanks a lot.

Suggestion: isn't it better to call the two methods `onShown` and `onHidden`, so as to maintain the same coding style of the other `Dockable` event-listener methods? (`onDocked`, `onUnpinning` etc...)

**Comment by andrewauclair** [comment]
That does sound like a better idea. Not sure why I went with just `shown` and `hidden`. I'll put in a change to make it consistent.

**Comment by tlf30** [comment]
Talking about naming, it would be great to have all the getters and setters follow java's property naming convention. While this convention is not as elegant as the current names, it does make it compatible with java's property change bindings, which is what swing uses for its components. 

Another thing I would love to see is all these event functions migrated to swing listeners. Not sure how that would work as an interface, I currently have a wrapper class that wraps all of them with swing listeners. Perhaps a similar wrapper could be provided in the future. I would have to think about the best way to go about this though.

**Comment by andrewauclair** [comment]
I believe I made a separate listener class. I'll have to double check that later.

For the bean bindings in JFormDesigner (I'm guessing that's what you're referring to again), I'm assuming they all need to start with get/set? I thought I had changed them all, but I see now that I must have skipped `Dockable`.

**Comment by andrewauclair** [comment]
> Talking about naming, it would be great to have all the getters and setters follow java's property naming convention. While this convention is not as elegant as the current names, it does make it compatible with java's property change bindings, which is what swing uses for its components.

Just did a bunch of name changes to make sure everything in `Dockable` is get/set. There is a class called `DefaultDockingPanel` which implements `Dockable` and adds a set for every get. Maybe that will be more useful now that everything is named better.

> Another thing I would love to see is all these event functions migrated to swing listeners. Not sure how that would work as an interface, I currently have a wrapper class that wraps all of them with swing listeners. Perhaps a similar wrapper could be provided in the future. I would have to think about the best way to go about this though.

There is `DockingListener` and `DockingListeners` where you register them. Which I just realized is internal. I thought I had developed something that was intended to be used outside of the framework. I'll look into this more.

**Comment by tlf30** [comment]
This is awesome, thank you.
Just reviewed the changes, just as the note, boolean getters should use `is` instead of `get` for property support. 
I'll do a more extensive review later tonight, currently wrapped up in some other work stuff 😥

**Comment by andrewauclair** [comment]
> This is awesome, thank you. Just reviewed the changes, just as the note, boolean getters should use `is` instead of `get` for property support. I'll do a more extensive review later tonight, currently wrapped up in some other work stuff 😥

Thanks! I couldn't remember if it could figure out `is`. I'll change the ones that make sense there.

Good luck with the work stuff.

**Comment by andrewauclair** [comment]
The new listener system is in 0.9.0.
