### ISSUE TITLE
Strange screen flickering on Linux

### ISSUE THREAD

**Issue by iXo** [andrewauclair/ModernDocking#68]
I noticed some strange flickering on Linux + Gnome + Jre 15.

As the visual studio helper doesn't to be mandatory as the panel is drawn too, is there a possibility to disable the panel location drop helper ?

https://github.com/andrewauclair/ModernDocking/assets/401900/b0d255a1-b55d-4123-91af-2fa90f942a7f

**Comment by andrewauclair** [comment]
Probably caused by the changes I've made trying to fix issue #65. I undid them for now, since they didn't fix that issue.

**Comment by andrewauclair** [comment]
> As the visual studio helper doesn't to be mandatory as the panel is drawn too, is there a possibility to disable the panel location drop helper ?
To answer your question. Through some research for #65 I believe I've discovered that I should be supporting some way to draw the handles differently when translucency/transparency is not supported.

**Comment by andrewauclair** [comment]
Interesting. Thanks for discovering that. I have made that change and I'm publishing a 0.6.1 right now for my own uses. I will be doing some testing on CentOS 7 and possibly Rocky Linux 8.4 this week.

At least I could very easily setup VMs of Linux machines (I tried setting up a macOS VM and it didn't work).

**Comment by andrewauclair** [comment]
@iXo Could you try this out again with the latest? I did some testing on Ubuntu 22.04 today and realized my special RepaintManager was causing an issue with transparency. Did you build your code from my sample and keep the `FailOnThreadViolationRepaintManager.install();` line of code? I wrote issue #72 for this and no longer install it by default in the sample.

**Comment by iXo** [comment]
Thank you very much ! Indeed I was using the EDT violation detector. And disabling it make the panels transparency works as expected.

**Comment by andrewauclair** [comment]
Awesome! I'm glad that's sorted out.
