### ISSUE TITLE
intellij dark theme from FlatLaf doesn't apply to docked panels tabs

### ISSUE THREAD

**Issue by iXo** [andrewauclair/ModernDocking#69]
As you can see in this screenshot, if using a dark theme from FlatLaf intellij plugin, the tabs are still white

![image](https://github.com/andrewauclair/ModernDocking/assets/401900/0ef08f84-c294-4938-a009-302ed73a3cce)

**Comment by andrewauclair** [comment]
Maybe it's the color I'm pulling from the theme. I'll check it out when I get home.

**Comment by andrewauclair** [comment]
The titlebar background color comes from a property named `ModernDocking.titlebar.background.color` which you need to add to the properties file for the theme. Or you can create a custom header UI and set the background color. That's what I do in the demo project.

**Comment by andrewauclair** [comment]
@iXo I'm working on an update to use some colors from the theme.

Currently I am planning to use `TableHeader.background` and `TableHeader.foreground` in `FlatLafHeaderUI` as well as `TableHeader.borderColor` for the border. I am going to rework the demo to include some more FlatLaf theme selections.

![image](https://github.com/andrewauclair/ModernDocking/assets/2949516/b13fb5d8-47d4-45d0-9843-42ed3c4d407a)

**Comment by andrewauclair** [comment]
Closing as I believe I've addressed all of the issues with switching themes.
