### ISSUE TITLE
NPE when trying to put back a floating window into the main app

### ISSUE THREAD

**Issue by iXo** [andrewauclair/ModernDocking#70]
On a modern docking enabled app, if a panel is set to window mode, when we try to put it back, it NPE :

> Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "ModernDocking.floating.TempFloatingFrame.toFront()" because "this.floatingFrame" is null
> 	at ModernDocking.floating.FloatListener.lambda$changeFrameOverlays$4(FloatListener.java:165)
> 	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
> 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
> 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
> 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
> Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "ModernDocking.floating.DockingUtilsFrame.toFront()" because "this.activeUtilsFrame" is null
> 	at ModernDocking.floating.FloatListener.lambda$changeFrameOverlays$5(FloatListener.java:166)
> 	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
> 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
> 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
> 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by andrewauclair** [comment]
Most likely happening because of a `SwingUtilities.invokeLater` and the frame gets set to null before it happens. I've wrapped them better with null checks.

**Comment by andrewauclair** [comment]
Fixed in 0.7.2
