### ISSUE TITLE
Theme Not Changing On Hidden Dockables Displayed

### ISSUE THREAD

**Issue by andrewauclair** [andrewauclair/ModernDocking#74]
Dockables that are not being displayed are not part of the UI tree. Anything not part of the tree when the look and feel changes does not get updated. Modern Docking needs to handle this properly by manually updating the hidden dockables.

**Comment by tlf30** [comment]
This would be great to get fixed. I currently keep a list of all dockables and I added a theme change event listener that is registered on each dockable to update them when the theme changes.

**Comment by andrewauclair** [comment]
Agreed. I just noticed it in the demo. My real apps don't support switching on the fly just yet (coming soonish) so I haven't noticed in my testing.

**Comment by andrewauclair** [comment]
Verified, fixed in 0.7.1.
