### ISSUE TITLE
Docking.clear()

### ISSUE THREAD

**Issue by tlf30** [andrewauclair/ModernDocking#76]
Hello, could you add a function, something like `Docking.clear()` or `Docking.reset()` which would clear everything that is registered?

I am trying to implement a soft restart function to my app, and there is no easy way to unregister everything, having a clear function would make things very simple. 

Thank you,
Trevor

**Comment by andrewauclair** [comment]
Sounds good to me. I think it would have to deregister all dockables and undock them from all the roots.

I'll leave the roots alone and not deregister those.

**Comment by andrewauclair** [comment]
I think while I'm at it I'll add a way to access a list of all registered dockables. That should make it a bit easier to deal with if you need to write any temporary workarounds in the future like you mentioned in issue #74.

**Comment by tlf30** [comment]
Sounds good, a way to unregister all roots would be desirable too. In my case all my windows have been disposed of.

**Comment by andrewauclair** [comment]
> Sounds good, a way to unregister all roots would be desirable too. In my case all my windows have been disposed of.

This makes me realize that I assume the framework is managing all windows that aren't the main window and I'm disposing them in certain cases. I'll clean that up and make sure I only dispose the windows I create.

**Comment by andrewauclair** [comment]
Made some more improvements to this for the next release. Dockables that can't be closed were being redocked after undocking in the deregister.
