### ISSUE TITLE
Is there a possibility to reset the docking system as it was from code ?

### ISSUE THREAD

**Issue by iXo** [andrewauclair/ModernDocking#79]
Let's say someone moved some panel and want to cancel what he did because the gui is now unusable and he want to restart from scratch, is there a possibility to make the docking system reset itself before any user modifications ? Like if the persist file would not be present.

**Comment by andrewauclair** [comment]
I think this could be achieved with the `DockingLayouts` class and default layout given to `AppState`. What I typically do is use the `WindowLayoutBuilder` to build what I want as a default layout and I set that with `AppState.setDefaultApplicationLayout`. This can be seen in the basic demo `MainFrame.java`.

`DockingLayouts` lets you build and store as many named layouts as you wish. It can be tied to menu items that restore the named layout. This can also be seen in the demo using the default layout.

In terms of an undo system, there currently is no support for one. In theory that could be supported through a new listener that gets notified when the persist timer goes off and persists a new layout. The app could then track a series of `ApplicationLayout`s and have some undo system features.

**Comment by iXo** [comment]
My main code is creating a layout using the `WindowLayoutBuilder`, and set it like that : `DockingLayouts.addLayout("default", defaultLayout); AppState.setDefaultApplicationLayout(defaultLayout);`

This is always called before calling `AppState.restore();AppState.setAutoPersist(true);`.

On a menu item, I tried to call this code : `AppState.setDefaultApplicationLayout(DockingLayouts.getLayout("default"));` but this doesn't seems to reset the layout to the position it is when the persist file doesn't exists.

Do I miss something ?

**Comment by iXo** [comment]
Ok, my should be in fact `DockingState.restoreApplicationLayout(DockingLayouts.getLayout("default"));` and it works fine

**Comment by iXo** [comment]
Sorry to have bother you.

**Comment by andrewauclair** [comment]
No worries. I have a severe lack of general documentation right now. I think the code still needs to be organized a little better. The layout stuff feels all over the place.
