### ISSUE TITLE
Add More Control Over Unpinned Toolbars

### ISSUE THREAD

**Issue by andrewauclair** [andrewauclair/ModernDocking#85]
Give the app more say in which unpinned toolbars are available and which one a dockable might be displayed in.

**Comment by dansef83** [comment]
It would be great if you add some of the following ideas.


https://github.com/andrewauclair/ModernDocking/assets/146780976/075bd161-9168-44d9-8cf2-c66db66078bf

**Comment by andrewauclair** [comment]
Each toolbar can now be enabled or disabled, the dockable can set which of the toolbars it's allowed in and there are now handles for pinning. This should be a good amount of control for now.
