### ISSUE TITLE
how to open a float dockable?

### ISSUE THREAD

**Issue by nicqchen** [andrewauclair/ModernDocking#86]

**Comment by andrewauclair** [comment]
There are several ways to float dockables.

1. Programmatically by call `Docking.newWindow` with the dockable.
1. User interaction by selecting the `Window` option on the settings menu of the dockable.
1. User interaction by physically dragging and dropping the window somewhere outside of existing frames.

Note that the dockable must return true for `isFloatingAllowed` for these to work.

Example of 3 can be seen here: https://github.com/andrewauclair/ModernDocking/blob/main/img/floating_panel.gif

**Comment by nicqchen** [comment]
thanks, could i have programmatically codes example?

**Comment by andrewauclair** [comment]
> thanks, could i have programmatically codes example?

I just added a sample for it, [Floating Sample](https://github.com/andrewauclair/ModernDocking/blob/1e18c2dce255920cd0138278f8fa086ce08e305d/demo/src/basic/FloatingSample.java)
